name: plant_it
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  provider: ^6.0.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  intl: ^0.18.1
  flutter_colorpicker: ^1.1.0
  http: ^1.3.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  firebase_storage: ^11.2.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.14.3  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Drawing.png

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/images/newlogo3.png  # Your splash image
  android: true
  ios: true
  android_12:
    image: assets/images/newlogo3.png  # For Android 12+
    icon_background_color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/newlogo3.png"
