// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj_L0EKWBggCEF6LQu6eVNI3unU05zByA',
    appId: '1:680306707405:web:7739fdc03cc99c6260d284',
    messagingSenderId: '680306707405',
    projectId: 'planit-13175',
    authDomain: 'planit-13175.firebaseapp.com',
    storageBucket: 'planit-13175.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvOU812iCU_ufiPHZ8TBDZRy5U1ugKWo',
    appId: '1:680306707405:android:fe377fc8143dc45160d284',
    messagingSenderId: '680306707405',
    projectId: 'planit-13175',
    storageBucket: 'planit-13175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_A6G4y-1m0Vd4mrM-2c-7tpNsGhAcLi0',
    appId: '1:680306707405:ios:845bdadc03d9073e60d284',
    messagingSenderId: '680306707405',
    projectId: 'planit-13175',
    storageBucket: 'planit-13175.firebasestorage.app',
    iosBundleId: 'com.example.plantIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_A6G4y-1m0Vd4mrM-2c-7tpNsGhAcLi0',
    appId: '1:680306707405:ios:845bdadc03d9073e60d284',
    messagingSenderId: '680306707405',
    projectId: 'planit-13175',
    storageBucket: 'planit-13175.firebasestorage.app',
    iosBundleId: 'com.example.plantIt',
  );
}
